-- RestMex IT MVP database schema for Supabase/PostgreSQL
-- Source of truth: ARCHITECTURE_REVIEW.md, DATABASE_SCHEMA.md, MVP_PLAN.md
-- Phase 1 intentionally excludes Telegram AI tables.

create extension if not exists pgcrypto;

-- =========================
-- Enum types
-- =========================

do $$
begin
  if not exists (select 1 from pg_type where typname = 'user_role') then
    create type public.user_role as enum (
      'admin',
      'manager',
      'executor',
      'viewer'
    );
  end if;
end;
$$;

do $$
begin
  if not exists (select 1 from pg_type where typname = 'request_status') then
    create type public.request_status as enum (
      'needs_planning',
      'needs_review',
      'planned',
      'in_progress',
      'waiting_client',
      'specialist_on_way',
      'waiting_parts',
      'outsource',
      'postponed',
      'done',
      'cancelled',
      'duplicate',
      'not_actual'
    );
  end if;
end;
$$;

do $$
begin
  if not exists (select 1 from pg_type where typname = 'request_type') then
    create type public.request_type as enum (
      'repair',
      'maintenance',
      'installation',
      'diagnostics',
      'delivery',
      'consultation',
      'other'
    );
  end if;
end;
$$;

do $$
begin
  if not exists (select 1 from pg_type where typname = 'urgency_level') then
    create type public.urgency_level as enum (
      'low',
      'normal',
      'high',
      'critical'
    );
  end if;
end;
$$;

do $$
begin
  if not exists (select 1 from pg_type where typname = 'request_source') then
    create type public.request_source as enum (
      'manual',
      'import',
      'other'
    );
  end if;
end;
$$;

do $$
begin
  if not exists (select 1 from pg_type where typname = 'attachment_source') then
    create type public.attachment_source as enum (
      'manual',
      'import',
      'other'
    );
  end if;
end;
$$;

do $$
begin
  if not exists (select 1 from pg_type where typname = 'attachment_file_type') then
    create type public.attachment_file_type as enum (
      'photo',
      'video',
      'document',
      'audio',
      'other'
    );
  end if;
end;
$$;

do $$
begin
  if not exists (select 1 from pg_type where typname = 'close_result') then
    create type public.close_result as enum (
      'completed',
      'cancelled',
      'duplicate',
      'not_actual',
      'transferred'
    );
  end if;
end;
$$;

-- =========================
-- Utility functions
-- =========================

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- =========================
-- Tables
-- =========================

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null,
  role public.user_role not null default 'viewer',
  phone text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.locations (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  address text,
  city text,
  client_name text,
  contact text,
  phone text,
  yandex_maps_url text,
  working_hours text,
  notes text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.location_tags (
  id uuid primary key default gen_random_uuid(),
  location_id uuid not null references public.locations(id) on delete cascade,
  tag text not null,
  created_at timestamptz not null default now(),
  constraint location_tags_location_tag_unique unique (location_id, tag)
);

create table if not exists public.requests (
  id uuid primary key default gen_random_uuid(),
  request_number bigint generated by default as identity unique,
  location_id uuid references public.locations(id) on delete set null,
  title text,
  description text not null,
  request_type public.request_type not null default 'other',
  urgency public.urgency_level not null default 'normal',
  status public.request_status not null default 'needs_planning',
  source public.request_source not null default 'manual',
  created_by uuid references public.profiles(id) on delete set null,
  reported_by_name text,
  planned_date date,
  start_time time,
  end_time time,
  queue_position integer,
  assigned_to uuid references public.profiles(id) on delete set null,
  outsource_contractor text,
  outsource_comment text,
  manager_comment text,
  executor_comment text,
  closed_at timestamptz,
  closed_by uuid references public.profiles(id) on delete set null,
  close_result public.close_result,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint requests_queue_position_positive check (queue_position is null or queue_position > 0)
);

create table if not exists public.request_comments (
  id uuid primary key default gen_random_uuid(),
  request_id uuid not null references public.requests(id) on delete cascade,
  author_id uuid references public.profiles(id) on delete set null,
  body text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.request_events (
  id uuid primary key default gen_random_uuid(),
  request_id uuid not null references public.requests(id) on delete cascade,
  actor_id uuid references public.profiles(id) on delete set null,
  event_type text not null,
  from_value jsonb,
  to_value jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.attachments (
  id uuid primary key default gen_random_uuid(),
  request_id uuid not null references public.requests(id) on delete cascade,
  uploaded_by uuid references public.profiles(id) on delete set null,
  source public.attachment_source not null default 'manual',
  storage_path text not null,
  file_name text,
  mime_type text,
  file_type public.attachment_file_type not null default 'other',
  created_at timestamptz not null default now()
);

-- =========================
-- Updated_at triggers
-- =========================

drop trigger if exists set_profiles_updated_at on public.profiles;
create trigger set_profiles_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists set_locations_updated_at on public.locations;
create trigger set_locations_updated_at
before update on public.locations
for each row execute function public.set_updated_at();

drop trigger if exists set_requests_updated_at on public.requests;
create trigger set_requests_updated_at
before update on public.requests
for each row execute function public.set_updated_at();

-- =========================
-- Indexes
-- =========================

create index if not exists profiles_role_idx on public.profiles(role);
create index if not exists profiles_is_active_idx on public.profiles(is_active);

create index if not exists locations_name_idx on public.locations(name);
create index if not exists locations_city_idx on public.locations(city);
create index if not exists locations_is_active_idx on public.locations(is_active);

create index if not exists location_tags_location_id_idx on public.location_tags(location_id);
create index if not exists location_tags_tag_idx on public.location_tags(tag);

create index if not exists requests_status_idx on public.requests(status);
create index if not exists requests_planned_date_idx on public.requests(planned_date);
create index if not exists requests_assigned_to_idx on public.requests(assigned_to);
create index if not exists requests_location_id_idx on public.requests(location_id);
create index if not exists requests_created_by_idx on public.requests(created_by);
create index if not exists requests_closed_by_idx on public.requests(closed_by);
create index if not exists requests_created_at_idx on public.requests(created_at);
create index if not exists requests_planned_queue_idx on public.requests(planned_date, queue_position);
create index if not exists requests_active_status_idx
  on public.requests(status, planned_date)
  where status not in ('done', 'cancelled', 'duplicate', 'not_actual');

create index if not exists request_comments_request_id_idx on public.request_comments(request_id);
create index if not exists request_comments_author_id_idx on public.request_comments(author_id);
create index if not exists request_comments_created_at_idx on public.request_comments(created_at);

create index if not exists request_events_request_id_idx on public.request_events(request_id);
create index if not exists request_events_actor_id_idx on public.request_events(actor_id);
create index if not exists request_events_event_type_idx on public.request_events(event_type);
create index if not exists request_events_created_at_idx on public.request_events(created_at);

create index if not exists attachments_request_id_idx on public.attachments(request_id);
create index if not exists attachments_uploaded_by_idx on public.attachments(uploaded_by);
create index if not exists attachments_file_type_idx on public.attachments(file_type);

-- =========================
-- Views
-- =========================

create or replace view public.new_requests_view as
select
  r.*,
  l.name as location_name,
  l.address as location_address,
  l.city as location_city,
  assignee.full_name as assigned_to_name,
  creator.full_name as created_by_name
from public.requests r
left join public.locations l on l.id = r.location_id
left join public.profiles assignee on assignee.id = r.assigned_to
left join public.profiles creator on creator.id = r.created_by
where r.status in ('needs_planning', 'needs_review');

create or replace view public.mechanic_current_tasks_view as
select
  r.*,
  l.name as location_name,
  l.address as location_address,
  l.city as location_city,
  assignee.full_name as assigned_to_name
from public.requests r
left join public.locations l on l.id = r.location_id
left join public.profiles assignee on assignee.id = r.assigned_to
where r.planned_date = current_date
  and r.status in ('planned', 'in_progress', 'waiting_client')
order by
  r.queue_position asc nulls last,
  case r.urgency
    when 'critical' then 1
    when 'high' then 2
    when 'normal' then 3
    when 'low' then 4
  end,
  r.created_at asc;

create or replace view public.outsource_requests_view as
select
  r.*,
  l.name as location_name,
  l.address as location_address,
  l.city as location_city,
  assignee.full_name as assigned_to_name
from public.requests r
left join public.locations l on l.id = r.location_id
left join public.profiles assignee on assignee.id = r.assigned_to
where r.status = 'specialist_on_way';

create or replace view public.closed_requests_view as
select
  r.*,
  l.name as location_name,
  l.address as location_address,
  l.city as location_city,
  assignee.full_name as assigned_to_name,
  closer.full_name as closed_by_name
from public.requests r
left join public.locations l on l.id = r.location_id
left join public.profiles assignee on assignee.id = r.assigned_to
left join public.profiles closer on closer.id = r.closed_by
where r.status in ('done', 'cancelled', 'duplicate', 'not_actual');

-- =========================
-- Row Level Security
-- =========================
-- These MVP policies keep access simple while the product is internal.
-- Tighten them before adding external users or customer-facing access.
-- The first UI iteration has no sign-in yet, so anon access is allowed
-- for MVP testing. Replace anon policies with authenticated role checks
-- when authentication is added.

alter table public.profiles enable row level security;
alter table public.locations enable row level security;
alter table public.location_tags enable row level security;
alter table public.requests enable row level security;
alter table public.request_comments enable row level security;
alter table public.request_events enable row level security;
alter table public.attachments enable row level security;

drop policy if exists "Authenticated users can read profiles" on public.profiles;
create policy "Authenticated users can read profiles"
on public.profiles for select
to authenticated
using (true);

drop policy if exists "MVP anon can read profiles" on public.profiles;
create policy "MVP anon can read profiles"
on public.profiles for select
to anon
using (true);

drop policy if exists "Users can update their own profile" on public.profiles;
create policy "Users can update their own profile"
on public.profiles for update
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

drop policy if exists "Authenticated users can read locations" on public.locations;
create policy "Authenticated users can read locations"
on public.locations for select
to authenticated
using (true);

drop policy if exists "Authenticated users can manage locations" on public.locations;
create policy "Authenticated users can manage locations"
on public.locations for all
to authenticated
using (true)
with check (true);

drop policy if exists "MVP anon can read locations" on public.locations;
create policy "MVP anon can read locations"
on public.locations for select
to anon
using (true);

drop policy if exists "MVP anon can create locations" on public.locations;
create policy "MVP anon can create locations"
on public.locations for insert
to anon
with check (true);

drop policy if exists "MVP anon can update locations" on public.locations;
create policy "MVP anon can update locations"
on public.locations for update
to anon
using (true)
with check (true);

drop policy if exists "Authenticated users can read location tags" on public.location_tags;
create policy "Authenticated users can read location tags"
on public.location_tags for select
to authenticated
using (true);

drop policy if exists "Authenticated users can manage location tags" on public.location_tags;
create policy "Authenticated users can manage location tags"
on public.location_tags for all
to authenticated
using (true)
with check (true);

drop policy if exists "Authenticated users can read requests" on public.requests;
create policy "Authenticated users can read requests"
on public.requests for select
to authenticated
using (true);

drop policy if exists "MVP anon can read requests" on public.requests;
create policy "MVP anon can read requests"
on public.requests for select
to anon
using (true);

drop policy if exists "Authenticated users can manage requests" on public.requests;
create policy "Authenticated users can manage requests"
on public.requests for all
to authenticated
using (true)
with check (true);

drop policy if exists "MVP anon can create requests" on public.requests;
create policy "MVP anon can create requests"
on public.requests for insert
to anon
with check (true);

drop policy if exists "MVP anon can update requests" on public.requests;
create policy "MVP anon can update requests"
on public.requests for update
to anon
using (true)
with check (true);

drop policy if exists "Authenticated users can read request comments" on public.request_comments;
create policy "Authenticated users can read request comments"
on public.request_comments for select
to authenticated
using (true);

drop policy if exists "Authenticated users can manage request comments" on public.request_comments;
create policy "Authenticated users can manage request comments"
on public.request_comments for all
to authenticated
using (true)
with check (true);

drop policy if exists "Authenticated users can read request events" on public.request_events;
create policy "Authenticated users can read request events"
on public.request_events for select
to authenticated
using (true);

drop policy if exists "Authenticated users can create request events" on public.request_events;
create policy "Authenticated users can create request events"
on public.request_events for insert
to authenticated
with check (true);

drop policy if exists "Authenticated users can read attachments" on public.attachments;
create policy "Authenticated users can read attachments"
on public.attachments for select
to authenticated
using (true);

drop policy if exists "Authenticated users can manage attachments" on public.attachments;
create policy "Authenticated users can manage attachments"
on public.attachments for all
to authenticated
using (true)
with check (true);

grant usage on schema public to anon, authenticated;
grant select on public.profiles to anon, authenticated;
grant select, insert, update on public.locations to anon, authenticated;
grant select on public.location_tags to anon, authenticated;
grant select, insert, update on public.requests to anon, authenticated;
grant select, insert on public.request_comments to anon, authenticated;
grant select, insert on public.request_events to anon, authenticated;
grant select, insert on public.attachments to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;
